Repository Kernel360/E2E1-TaskTracker, pull requests merged in 2023-10, with the labels that each got.

#1 [docs] 계층 구조 readme
  docs/README.md
Labels: 📖 Docs, 🚀 이종찬

#3 [ADD] project setting
  proejct/.gitignore
  proejct/build.gradle
  proejct/gradle/wrapper/gradle-wrapper.jar
  proejct/gradle/wrapper/gradle-wrapper.properties
  proejct/gradlew
  proejct/gradlew.bat
  proejct/settings.gradle
  proejct/src/main/java/org/fastcampus/proejct/ProejctApplication.java
  proejct/src/main/java/org/fastcampus/proejct/controller/MainController.java
  proejct/src/main/resources/application.yml
  proejct/src/test/java/org/fastcampus/proejct/ProejctApplicationTests.java
Labels: 🧑‍💻 Feature, 🚀 이종찬

#6 [FEAT] BoardRepositoryTest
  proejct/src/main/java/org/fastcampus/proejct/board/domain/Board.java
  proejct/src/main/java/org/fastcampus/proejct/board/dto/BoardDto.java
  proejct/src/main/java/org/fastcampus/proejct/board/repository/BoardRepository.java
  proejct/src/main/java/org/fastcampus/proejct/global/domain/BaseEntity.java
  proejct/src/test/java/org/fastcampus/proejct/board/repository/BoardRepositoryTest.java
Labels: ✅ Test, 🚀 이종찬

#9 [FEAT] UserRepository 생성
  proejct/src/main/java/org/fastcampus/proejct/user/domain/User.java
  proejct/src/main/java/org/fastcampus/proejct/user/dto/UserDto.java
  proejct/src/main/java/org/fastcampus/proejct/user/repository/UserRepository.java
Labels: ✅ Test, 🚀 홍주광

#11 Fix/#10 user
  proejct/src/main/java/org/fastcampus/proejct/board/domain/Board.java
  proejct/src/main/java/org/fastcampus/proejct/board/dto/BoardDto.java
  proejct/src/main/java/org/fastcampus/proejct/board/service/BoardService.java
  proejct/src/main/java/org/fastcampus/proejct/user/domain/User.java
  proejct/src/main/java/org/fastcampus/proejct/user/domain/UserInfo.java
  proejct/src/main/java/org/fastcampus/proejct/user/dto/UserDto.java
  proejct/src/main/java/org/fastcampus/proejct/user/dto/UserInfoDto.java
  proejct/src/main/java/org/fastcampus/proejct/user/repository/UserRepository.java
  proejct/src/test/java/org/fastcampus/proejct/board/service/BoardServiceTest.java
Labels: 🧑‍💻 Feature, 🚀 이종찬

#15 Feature/#14 board list connect
  proejct/src/main/java/org/fastcampus/proejct/board/controller/BoardRestController.java
  proejct/src/main/java/org/fastcampus/proejct/board/dto/ResponseBoardDto.java
  proejct/src/main/resources/templates/tables.html
  proejct/src/test/java/org/fastcampus/proejct/board/controller/BoardControllerTest.java
Labels: 🧑‍💻 Feature, 🚀 이종찬

#23 Feature/#20 board update
  proejct/src/main/java/org/fastcampus/proejct/board/domain/Board.java
  proejct/src/main/java/org/fastcampus/proejct/board/domain/Task.java
  proejct/src/main/java/org/fastcampus/proejct/board/dto/BoardDto.java
  proejct/src/main/java/org/fastcampus/proejct/board/dto/SortType.java
  proejct/src/main/java/org/fastcampus/proejct/board/dto/TaskDto.java
  proejct/src/main/java/org/fastcampus/proejct/board/repository/BoardRepository.java
  proejct/src/main/java/org/fastcampus/proejct/board/repository/TaskRepository.java
  proejct/src/main/java/org/fastcampus/proejct/board/repository/UserInfoRepository.java
  proejct/src/main/java/org/fastcampus/proejct/board/service/BoardService.java
  proejct/src/main/java/org/fastcampus/proejct/board/service/TaskService.java
  proejct/src/main/java/org/fastcampus/proejct/user/repository/UserInfoRepository.java
  proejct/src/test/java/org/fastcampus/proejct/board/service/BoardServiceTest.java
Labels: 🧑‍💻 Feature, 🚀 이종찬

#25 할일(Task) 기능 추가
  proejct/build.gradle
  proejct/src/main/java/org/fastcampus/proejct/board/controller/BoardController.java
  proejct/src/main/java/org/fastcampus/proejct/board/controller/BoardRestController.java
  proejct/src/main/java/org/fastcampus/proejct/board/controller/TaskController.java
  proejct/src/main/java/org/fastcampus/proejct/board/converter/SortType.java
  proejct/src/main/java/org/fastcampus/proejct/board/converter/dto/BoardDto.java
  proejct/src/main/java/org/fastcampus/proejct/board/converter/dto/TaskDto.java
  proejct/src/main/java/org/fastcampus/proejct/board/converter/response/ResponseBoardDto.java
  proejct/src/main/java/org/fastcampus/proejct/board/db/model/Board.java
  proejct/src/main/java/org/fastcampus/proejct/board/db/model/Task.java
  proejct/src/main/java/org/fastcampus/proejct/board/db/repository/BoardRepository.java
  proejct/src/main/java/org/fastcampus/proejct/board/db/repository/TaskRepository.java
  proejct/src/main/java/org/fastcampus/proejct/board/service/BoardService.java
  proejct/src/main/java/org/fastcampus/proejct/board/service/TaskService.java
  proejct/src/main/java/org/fastcampus/proejct/user/converter/dto/UserInfoDto.java
  proejct/src/main/java/org/fastcampus/proejct/user/db/model/UserInfo.java
  proejct/src/main/java/org/fastcampus/proejct/user/db/repository/UserInfoRepository.java
  proejct/src/main/resources/application.yml
  proejct/src/test/java/org/fastcampus/proejct/board/controller/BoardRestControllerTest.java
  proejct/src/test/java/org/fastcampus/proejct/board/repository/BoardRepositoryTest.java
  proejct/src/test/java/org/fastcampus/proejct/board/service/BoardServiceTest.java
  proejct/src/test/java/org/fastcampus/proejct/board/service/TaskServiceTest.java
Labels: 🧑‍💻 Feature, 🚀 이종찬

#27 알림 로직 DTO 추가 및 테스트 코드 수정
  proejct/src/main/java/org/fastcampus/proejct/global/dto/NotificationDto.java
  proejct/src/main/java/org/fastcampus/proejct/global/dto/TemplateCollection.java
  proejct/src/main/java/org/fastcampus/proejct/global/service/NotificationService.java
  proejct/src/test/java/org/fastcampus/proejct/global/service/NotificationServiceTest.java
Labels: ✅ Test, 🚀 정지용
