Repository Kernel360/E2E1-TaskTracker, pull requests merged in 2023-11, with the labels that each got.

#29 Feature/#28 security setting
  proejct/build.gradle
  proejct/src/main/java/org/fastcampus/proejct/ProejctApplication.java
  proejct/src/main/java/org/fastcampus/proejct/board/db/model/Board.java
  proejct/src/main/java/org/fastcampus/proejct/board/db/model/Task.java
  proejct/src/main/java/org/fastcampus/proejct/global/MainController.java
  proejct/src/main/java/org/fastcampus/proejct/global/config/RedisConfig.java
  proejct/src/main/java/org/fastcampus/proejct/global/config/SecurityConfig.java
  proejct/src/main/java/org/fastcampus/proejct/global/jpa/JpaConfig.java
  proejct/src/main/java/org/fastcampus/proejct/global/security/SecurityConfig.java
  proejct/src/main/java/org/fastcampus/proejct/home/controller/MainController.java
  proejct/src/main/java/org/fastcampus/proejct/home/db/model/BaseEntity.java
  proejct/src/main/java/org/fastcampus/proejct/user/converter/dto/KakaoAccountDto.java
  proejct/src/main/java/org/fastcampus/proejct/user/converter/dto/UserInfoDto.java
  proejct/src/main/java/org/fastcampus/proejct/user/converter/dto/UserPrincipal.java
  proejct/src/main/java/org/fastcampus/proejct/user/converter/response/KakaoResponse.java
  proejct/src/main/java/org/fastcampus/proejct/user/db/model/UserInfo.java
  proejct/src/main/java/org/fastcampus/proejct/user/db/repository/UserInfoRepository.java
  proejct/src/main/java/org/fastcampus/proejct/user/service/UserInfoService.java
  proejct/src/main/resources/application.yml
Labels: 🧑‍💻 Feature, 🚀 이종찬

#33 Feat/board controller test
  proejct/src/main/java/org/fastcampus/proejct/board/controller/BoardRestController.java
  proejct/src/main/java/org/fastcampus/proejct/data.sql
  proejct/src/main/java/org/fastcampus/proejct/global/domain/NotificationEntity.java
  proejct/src/test/java/org/fastcampus/proejct/board/controller/BoardControllerTest.java
Labels: ✅ Test, 🚀 홍주광

#43 관리자페이지 레이아웃 분할, 통계 대시보드 추가
  proejct/src/main/java/org/fastcampus/proejct/board/controller/BoardRestController.java
  proejct/src/main/resources/templates/admin_left.html
  proejct/src/main/resources/templates/index.html
Labels: 🧑‍💻 Feature, 🚀 정지용

#44 Board 도메인 수정 및 정렬 기능 추가
  proejct/src/main/java/org/fastcampus/proejct/auth/converter/dto/UserInfoDto.java
  proejct/src/main/java/org/fastcampus/proejct/board/controller/BoardRestController.java
  proejct/src/main/java/org/fastcampus/proejct/board/converter/SortType.java
  proejct/src/main/java/org/fastcampus/proejct/board/converter/dto/BoardDto.java
  proejct/src/main/java/org/fastcampus/proejct/board/converter/dto/BoardMemberDto.java
  proejct/src/main/java/org/fastcampus/proejct/board/db/model/Board.java
  proejct/src/main/java/org/fastcampus/proejct/board/db/model/BoardMember.java
  proejct/src/main/java/org/fastcampus/proejct/board/db/repository/BoardRepository.java
  proejct/src/main/java/org/fastcampus/proejct/board/service/BoardService.java
  proejct/src/main/java/org/fastcampus/proejct/user/db/model/UserInfo.java
  proejct/src/main/java/org/fastcampus/proejct/user/service/UserInfoService.java
Labels: 🧑‍💻 Feature, 🚀 이종찬

#47 Feat/friend
  proejct/src/main/java/org/fastcampus/proejct/board/controller/BoardController.java
  proejct/src/main/java/org/fastcampus/proejct/friend/controller/FriendController.java
  proejct/src/main/java/org/fastcampus/proejct/friend/converter/FriendDto.java
  proejct/src/main/java/org/fastcampus/proejct/friend/db/model/Friend.java
  proejct/src/main/java/org/fastcampus/proejct/friend/db/repository/FriendRepository.java
  proejct/src/main/java/org/fastcampus/proejct/friend/service/FriendService.java
  proejct/src/main/java/org/fastcampus/proejct/global/fcm/FCMConfig.java
  proejct/src/main/java/org/fastcampus/proejct/global/fcm/FCMNotificationRequestDto.java
  proejct/src/main/java/org/fastcampus/proejct/user/db/model/UserInfo.java
  proejct/src/main/resources/application.yml
  proejct/src/main/resources/templates/friends.html
  proejct/src/main/resources/templates/index.html
  proejct/src/main/resources/templates/tables.html
  proejct/src/test/java/org/fastcampus/proejct/board/controller/BoardControllerTest.java
Labels: 🧑‍💻 Feature, 🚀 홍주광, 🐛 FIX / BUG

#52 Feat admin
  proejct/src/main/resources/templates/login.html
Labels: 🚀 정지용, Chore

#60 Feature/#59 delete view setting
  proejct/src/main/java/org/fastcampus/proejct/auth/controller/AuthController.java
  proejct/src/main/java/org/fastcampus/proejct/board/controller/BoardController.java
  proejct/src/main/resources/templates/board/detail.html
  proejct/src/main/resources/templates/board/detail.th.xml
  proejct/src/main/resources/templates/tables.html
Labels: 🧑‍💻 Feature, 🚀 이종찬

#63 [CHORE] 게시판 작성 페이지 뷰
  proejct/src/main/resources/templates/board/write.html
Labels: 🚀 홍주광, Chore

#64 Feature/#61 refactor response board
  proejct/src/main/java/org/fastcampus/proejct/board/controller/BoardController.java
  proejct/src/main/java/org/fastcampus/proejct/board/controller/BoardRestController.java
  proejct/src/main/java/org/fastcampus/proejct/board/converter/SortType.java
  proejct/src/main/java/org/fastcampus/proejct/board/db/repository/BoardRepository.java
  proejct/src/main/java/org/fastcampus/proejct/board/service/BoardService.java
  proejct/src/main/resources/templates/tables.html
Labels: 🧑‍💻 Feature, 🚀 이종찬

#66 [CHORE] 게시판 작성 페이지 뷰 수정
  proejct/src/main/resources/templates/board/write.html
Labels: 🚀 홍주광, Chore

#69 Feature/#68 notification
  proejct/src/main/java/org/fastcampus/proejct/board/controller/BoardController.java
  proejct/src/main/java/org/fastcampus/proejct/board/service/BoardService.java
  proejct/src/main/java/org/fastcampus/proejct/notification/service/NotificationService.java
  proejct/src/main/resources/templates/tables.html
Labels: 🧑‍💻 Feature, 🚀 이종찬

#70 [CHORE] 친구 목록 뷰
  proejct/src/main/resources/templates/tables.html
Labels: 🚀 홍주광, Chore

#72 #71 [feat] 게시글 조회 상세 삭제
  proejct/src/main/java/org/fastcampus/proejct/auth/converter/dto/UserPrincipal.java
  proejct/src/main/java/org/fastcampus/proejct/board/controller/BoardController.java
  proejct/src/main/java/org/fastcampus/proejct/board/controller/BoardRestController.java
  proejct/src/main/resources/templates/board/detail.html
  proejct/src/main/resources/templates/index.html
  proejct/src/main/resources/templates/tables.html
Labels: 🧑‍💻 Feature, 🚀 정지용, Chore

#73 [CHORE] 게시판 작성 뷰 수정
  proejct/src/main/resources/templates/board/write.html
Labels: 🚀 홍주광, Chore

#75 #74 [feat] 게시글 등록/수정 화면에서 맴버 추가관리 스크립트 작성
  proejct/src/main/resources/templates/board/write.html
Labels: 🚀 정지용, 🐛 FIX / BUG

#76 [CHORE] 게시판 작성 페이지 뷰 수정
  proejct/src/main/resources/templates/board/write.html
Labels: 🚀 홍주광, Chore

#77 Feature/#68 notification
  proejct/src/main/java/org/fastcampus/proejct/auth/controller/AuthController.java
  proejct/src/main/java/org/fastcampus/proejct/auth/converter/dto/UserPrincipal.java
  proejct/src/main/java/org/fastcampus/proejct/auth/converter/request/RequestBoardDto.java
  proejct/src/main/java/org/fastcampus/proejct/board/controller/BoardController.java
  proejct/src/main/java/org/fastcampus/proejct/board/controller/BoardRestController.java
  proejct/src/main/java/org/fastcampus/proejct/board/converter/dto/BoardDto.java
  proejct/src/main/java/org/fastcampus/proejct/board/converter/dto/TaskDto.java
  proejct/src/main/java/org/fastcampus/proejct/board/db/repository/BoardRepository.java
  proejct/src/main/java/org/fastcampus/proejct/board/service/BoardService.java
  proejct/src/main/java/org/fastcampus/proejct/board/service/TaskService.java
  proejct/src/main/java/org/fastcampus/proejct/global/config/SecurityConfig.java
  proejct/src/main/java/org/fastcampus/proejct/global/converter/RoleType.java
  proejct/src/main/java/org/fastcampus/proejct/global/exception/GlobalExceptionHandler.java
  proejct/src/main/java/org/fastcampus/proejct/home/controller/MainController.java
  proejct/src/main/java/org/fastcampus/proejct/home/controller/Redirect.java
  proejct/src/main/java/org/fastcampus/proejct/notification/controller/NotificationRestController.java
  proejct/src/main/java/org/fastcampus/proejct/notification/converter/dto/NotificationDto.java
  proejct/src/main/java/org/fastcampus/proejct/notification/db/model/Notification.java
  proejct/src/main/java/org/fastcampus/proejct/notification/db/repository/NotificationRepository.java
  proejct/src/main/java/org/fastcampus/proejct/notification/service/NotificationService.java
  proejct/src/main/resources/application.yml
  proejct/src/main/resources/firebase/tasktracker-7d58c-firebase-adminsdk-nc0pe-84d337f99b.json
  proejct/src/main/resources/templates/board/detail.html
  proejct/src/main/resources/templates/board/write.html
  proejct/src/main/resources/templates/tables.html
Labels: 🧑‍💻 Feature, 🚀 이종찬

#79 Feature/#78 jpa board refactor
  proejct/src/main/java/org/fastcampus/proejct/auth/controller/AuthController.java
  proejct/src/main/java/org/fastcampus/proejct/board/controller/BoardController.java
  proejct/src/main/java/org/fastcampus/proejct/board/converter/SortType.java
  proejct/src/main/java/org/fastcampus/proejct/board/converter/dto/BoardDto.java
  proejct/src/main/java/org/fastcampus/proejct/board/db/model/Board.java
  proejct/src/main/java/org/fastcampus/proejct/board/db/repository/BoardRepository.java
  proejct/src/main/java/org/fastcampus/proejct/board/service/BoardService.java
  proejct/src/main/java/org/fastcampus/proejct/global/config/SecurityConfig.java
  proejct/src/main/java/org/fastcampus/proejct/global/converter/RedirectType.java
  proejct/src/main/resources/application.yml
  proejct/src/main/resources/templates/tables.html
Labels: 🧑‍💻 Feature, 🚀 이종찬

#83 [feat] 등록시 할일 목록 같이 전송 되도록 코드 추가
  proejct/src/main/resources/banner.txt
  proejct/src/main/resources/templates/board/write.html
Labels: 🧑‍💻 Feature, 🚀 정지용

#86 slf4j & logback setting
  proejct/build.gradle
  proejct/src/main/java/org/fastcampus/proejct/board/controller/BoardController.java
  proejct/src/main/resources/application.yml
  proejct/src/main/resources/logback-spring.xml
Labels: 🧑‍💻 Feature, 🚀 정지용

#88 배포 스크립트 작성
  proejct/src/main/java/org/fastcampus/proejct/base/controller/BaseController.java
  proejct/src/main/java/org/fastcampus/proejct/base/controller/Redirect.java
  proejct/src/main/java/org/fastcampus/proejct/base/converter/BaseResponse.java
  proejct/src/main/java/org/fastcampus/proejct/base/converter/RedirectType.java
  proejct/src/main/java/org/fastcampus/proejct/base/converter/RoleType.java
  proejct/src/main/java/org/fastcampus/proejct/base/db/model/BaseEntity.java
  proejct/src/main/java/org/fastcampus/proejct/util/FormDataEncoder.java
  scripts/deploy.sh
Labels: 🚀 이종찬, Chore

#99 게시판 RestController 구현
  src/main/java/org/fastcampus/proejct/base/controller/BaseController.java
  src/main/java/org/fastcampus/proejct/base/converter/Api.java
  src/main/java/org/fastcampus/proejct/base/converter/RedirectType.java
  src/main/java/org/fastcampus/proejct/board/controller/BoardRestController.java
  src/main/java/org/fastcampus/proejct/board/service/BoardService.java
  src/main/java/org/fastcampus/proejct/global/config/SecurityConfig.java
  src/main/java/org/fastcampus/proejct/notification/controller/NotificationRestController.java
  taskTracker.2023-11-15.log
Labels: 🧑‍💻 Feature, 🚀 이종찬

#102 feat_admin 관리자 회원관리 추가
  src/main/java/org/fastcampus/proejct/ProejctApplication.java
  src/main/java/org/fastcampus/proejct/admin/controller/adminController.java
  src/main/java/org/fastcampus/proejct/admin/controller/adminRestController.java
  src/main/java/org/fastcampus/proejct/admin/db/repository/adminRepository.java
  src/main/java/org/fastcampus/proejct/admin/service/adminService.java
  src/main/java/org/fastcampus/proejct/auth/converter/dto/UserInfoDto.java
  src/main/java/org/fastcampus/proejct/auth/converter/request/RequestBoardDto.java
  src/main/java/org/fastcampus/proejct/board/converter/dto/BoardDto.java
  src/main/java/org/fastcampus/proejct/board/converter/dto/TaskDto.java
  src/main/java/org/fastcampus/proejct/board/db/model/Board.java
  src/main/java/org/fastcampus/proejct/board/db/model/Task.java
  src/main/java/org/fastcampus/proejct/user/db/repository/UserInfoRepository.java
  src/main/java/org/fastcampus/proejct/user/service/UserInfoService.java
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
  src/main/resources/templates/admin_left.html
  src/main/resources/templates/admin_top.html
  src/main/resources/templates/admin_users.html
  src/main/resources/templates/index.html
  taskTracker.2023-11-16.log
  taskTracker.2023-11-17.log
Labels: 🚀 정지용

#100 Board, Task 리팩터링
  C:/TT_Logs/taskTracker_logback.log
  src/main/java/org/fastcampus/proejct/auth/converter/dto/UserPrincipal.java
  src/main/java/org/fastcampus/proejct/auth/converter/request/RequestBoardDto.java
  src/main/java/org/fastcampus/proejct/board/controller/BoardController.java
  src/main/java/org/fastcampus/proejct/board/controller/BoardRestController.java
  src/main/java/org/fastcampus/proejct/board/controller/TaskController.java
  src/main/java/org/fastcampus/proejct/board/controller/TaskRestController.java
  src/main/java/org/fastcampus/proejct/board/converter/SortType.java
  src/main/java/org/fastcampus/proejct/board/converter/dto/BoardDto.java
  src/main/java/org/fastcampus/proejct/board/converter/dto/BoardMemberDto.java
  src/main/java/org/fastcampus/proejct/board/converter/dto/TaskDto.java
  src/main/java/org/fastcampus/proejct/board/converter/request/RequestBoard.java
  src/main/java/org/fastcampus/proejct/board/converter/request/RequestTask.java
  src/main/java/org/fastcampus/proejct/board/converter/response/ResponseBoardDto.java
  src/main/java/org/fastcampus/proejct/board/db/model/Board.java
  src/main/java/org/fastcampus/proejct/board/db/model/Task.java
  src/main/java/org/fastcampus/proejct/board/db/repository/TaskRepository.java
  src/main/java/org/fastcampus/proejct/board/service/BoardService.java
  src/main/java/org/fastcampus/proejct/board/service/TaskService.java
  src/main/java/org/fastcampus/proejct/notification/controller/NotificationRestController.java
  src/main/java/org/fastcampus/proejct/notification/service/NotificationService.java
  src/main/java/org/fastcampus/proejct/user/converter/UserInfoDto.java
  src/main/java/org/fastcampus/proejct/user/db/model/UserInfo.java
  src/main/java/org/fastcampus/proejct/user/service/UserInfoService.java
  src/main/resources/application.yml
  src/main/resources/templates/board/detail.html
  src/main/resources/templates/board/write.html
  src/test/java/org/fastcampus/proejct/board/service/BoardServiceTest.java
  src/test/java/org/fastcampus/proejct/global/security/TestSecurityConfig.java
Labels: 🧑‍💻 Feature, 🚀 이종찬

#103 [FEAT] 게시판 멤버 추가, 삭제, 조회
  src/main/java/org/fastcampus/proejct/board/controller/BoardRestController.java
  src/main/java/org/fastcampus/proejct/board/db/model/Board.java
  src/main/java/org/fastcampus/proejct/board/db/repository/BoardRepository.java
  src/main/java/org/fastcampus/proejct/board/service/BoardService.java
  src/main/resources/logback-spring.xml
Labels: 🧑‍💻 Feature, 🚀 이종찬

#104 [FEAT] 친구 기능 추가, 삭제, 조회
  .github/workflows/gradle.yml
  scripts/deploy.sh
  src/main/java/org/fastcampus/proejct/follow/controller/FollowController.java
  src/main/java/org/fastcampus/proejct/follow/converter/FollowDto.java
  src/main/java/org/fastcampus/proejct/follow/db/model/Follow.java
  src/main/java/org/fastcampus/proejct/follow/db/repository/FollowRepository.java
  src/main/java/org/fastcampus/proejct/follow/service/FollowService.java
Labels: 🧑‍💻 Feature, 🚀 홍주광

#106 chore_layout headder/top/left 분리
  .github/workflows/gradle.yml
  scripts/deploy.sh
  src/main/java/org/fastcampus/proejct/admin/controller/adminController.java
  src/main/java/org/fastcampus/proejct/auth/controller/AuthController.java
  src/main/java/org/fastcampus/proejct/base/controller/BaseController.java
  src/main/java/org/fastcampus/proejct/base/controller/Redirect.java
  src/main/java/org/fastcampus/proejct/board/controller/BoardController.java
  src/main/resources/logback-spring.xml
  src/main/resources/templates/admin_left.html
  src/main/resources/templates/header.html
  src/main/resources/templates/index.html
  src/main/resources/templates/left.html
  src/main/resources/templates/tables.html
  src/main/resources/templates/top.html
  src/main/resources/templates/users.html
  src/test/java/org/fastcampus/proejct/board/service/BoardServiceTest.java
Labels: Chore

#113 [FEAT] FollowController, FollowRestController 분리
  .github/workflows/gradle.yml
  scripts/deploy.sh
  src/main/java/org/fastcampus/proejct/follow/controller/FollowController.java
  src/main/java/org/fastcampus/proejct/follow/controller/FollowRestController.java
  src/main/resources/logback-spring.xml
  src/main/resources/templates/top.html
Labels: 🧑‍💻 Feature, 🚀 홍주광

#114 admin 회원정보 페이지 페이징 네비게이션 추가
  src/main/java/org/fastcampus/proejct/admin/controller/adminController.java
  src/main/java/org/fastcampus/proejct/user/db/repository/UserInfoRepository.java
  src/main/java/org/fastcampus/proejct/user/service/UserInfoService.java
  src/main/resources/templates/left.html
  src/main/resources/templates/users.html
Labels: 🚀 정지용, Chore

#118 Feature/#117 seperate board
  src/main/java/org/fastcampus/proejct/board/controller/BoardController.java
  src/main/java/org/fastcampus/proejct/board/controller/BoardRestController.java
  src/main/java/org/fastcampus/proejct/board/controller/TaskRestController.java
  src/main/java/org/fastcampus/proejct/board/db/model/Board.java
  src/main/java/org/fastcampus/proejct/board/service/BoardService.java
  src/main/resources/templates/board/detail.html
  src/main/resources/templates/users.html
Labels: 🧑‍💻 Feature, 🚀 이종찬

#124 admin 사용자 관리, 관리자 권한 (Y/N) 기능
  src/main/java/org/fastcampus/proejct/admin/controller/adminRestController.java
  src/main/java/org/fastcampus/proejct/user/db/repository/UserInfoRepository.java
  src/main/java/org/fastcampus/proejct/user/service/UserInfoService.java
  src/main/resources/templates/top.html
  src/main/resources/templates/users.html
Labels: 🧑‍💻 Feature, 🚀 정지용, 🐛 FIX / BUG

#125 [FEAT] 친구 추가 기능 구현
  src/main/resources/templates/top.html
Labels: 🧑‍💻 Feature, 🚀 홍주광

#126 top layer 친구 추가 후 팝업 닫는 버그 수정
  src/main/java/org/fastcampus/proejct/admin/controller/adminController.java
  src/main/resources/templates/top.html
  src/main/resources/templates/users.html
Labels: 🚀 홍주광, 🚀 정지용, 🐛 FIX / BUG

#127 [FEAT] 게시판 뷰 연동
  src/main/java/org/fastcampus/proejct/board/controller/BoardController.java
  src/main/java/org/fastcampus/proejct/board/controller/BoardRestController.java
  src/main/java/org/fastcampus/proejct/board/controller/TaskRestController.java
  src/main/java/org/fastcampus/proejct/follow/db/repository/FollowRepository.java
  src/main/java/org/fastcampus/proejct/follow/service/FollowService.java
  src/main/resources/templates/board/detail.html
Labels: 🧑‍💻 Feature, 🚀 이종찬

#136 Feature/#131 notification connect
  src/main/java/org/fastcampus/proejct/notification/controller/NotificationRestController.java
  src/main/java/org/fastcampus/proejct/notification/db/model/Notification.java
  src/main/java/org/fastcampus/proejct/notification/db/repository/NotificationRepository.java
  src/main/java/org/fastcampus/proejct/notification/service/NotificationService.java
  src/main/resources/templates/top.html
Labels: 🧑‍💻 Feature, 🚀 이종찬

#139 [FEAT] 친구 신청 알림 - 수락, 거절 기능
  src/main/java/org/fastcampus/proejct/notification/controller/NotificationRestController.java
  src/main/java/org/fastcampus/proejct/notification/db/repository/NotificationRepository.java
  src/main/java/org/fastcampus/proejct/notification/service/NotificationService.java
  src/main/resources/templates/top.html
Labels: 🧑‍💻 Feature, 🚀 홍주광

#141 Fix deploy env :: 배포 수행 정상 작동 되도록 수정
  .github/workflows/gradle.yml
  appspec.yml
  scripts/deploy.sh
Labels: 🚀 정지용, 🐛 FIX / BUG

#142 Feature/#131 notification connect
  build.gradle
  src/main/java/org/fastcampus/proejct/ProejctApplication.java
  src/main/java/org/fastcampus/proejct/auth/controller/AuthController.java
  src/main/java/org/fastcampus/proejct/base/controller/BaseController.java
  src/main/java/org/fastcampus/proejct/global/config/SecurityConfig.java
  src/main/java/org/fastcampus/proejct/global/config/ThymeleafConfig.java
  src/main/resources/application.yml
  src/main/resources/templates/login.html
  src/main/resources/templates/login.th.xml
Labels: 🧑‍💻 Feature, 🚀 이종찬
